### ISSUE TITLE
Need to call out that quotes cannot be used in this handler's webhook_url env var

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-slack-handler#28]
After running into some errors surrounding the webhook url in my config that looked like:
```
---
type: Handler
api_version: core/v2
metadata:
  name: slack-default
  namespace: default
spec:
  command: sensu-slack-handler --channel '#alerts' --username 'sensu'
  env_vars:
  - SLACK_WEBHOOK_URL='https://hooks.slack.com/services/ABCDEFG/HIJKLMNOP/1234567890'
  filters:
  - is_incident
  - not_silenced
  - no_contacts
  handlers: null
  runtime_assets:
  - sensu/sensu-slack-handler
  secrets: null
  timeout: 10
  type: pipe
```

I reached out to our engineering team, who advised that the slack golang library + yaml does not allow the env var to be surrounded by quotes. We need to ensure that we call this out in the readme.
